language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "pypy3"
install:
  - pip install nose coveralls
  - python setup.py -q install
script:
  - coverage run --source=ripozo setup.py nosetests
after_success:
  coveralls